"""Constants for inference services."""

# LLM Constants
CONTEXT_TEXT_MAX_LENGTH = 5000
SCREEN_CONTEXT_MAX_LENGTH = 2000
MEMORY_QUERY_RESULTS = 3

# Memory Service Constants
POOL_SIZE_DEFAULT = 4
POOL_ACQUIRE_TIMEOUT = 5.0
MEMORY_PRUNE_THRESHOLD = 10000
MEMORY_PRUNE_KEEP = 5000
UNIQUENESS_SAMPLE_SIZE = 1000
UNIQUENESS_NEIGHBOR_COUNT = 10
UNIQUENESS_DISTANCE_EPSILON = 0.001
DEDUP_SAMPLE_SIZE = 500
DEDUP_NEIGHBOR_COUNT = 5
MEMORY_QUERY_DEFAULT_RESULTS = 5

# VAD Constants
VAD_DEFAULT_THRESHOLD = 0.5
VAD_DEFAULT_SAMPLE_RATE = 16000

# Transcription Constants
WHISPER_BEAM_SIZE = 1

# Diarization Constants
DIARIZATION_MODEL = "pyannote/speaker-diarization-3.1"
DIARIZATION_MIN_SPEAKERS = 1

# Question Detection Constants
MIN_QUESTION_LENGTH = 10

# gRPC Server Constants
GRPC_MAX_WORKERS = 10
GRPC_SHUTDOWN_GRACE_PERIOD = 10
GRPC_DEFAULT_PORT = 50051

# Audio Processing
SAMPLES_PER_SECOND = 16000  # 16kHz standard

# Summarization
SUMMARY_MIN_INPUT_LENGTH = 200  # Minimum transcript length to summarize

