# golangci-lint configuration (v2 format for 2025)
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: false  # Don't lint test files
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  sort-results: true

formatters:
  enable:
    - gofmt
    - goimports
    - gci

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes:
        - github.com/good-listener

    gci:
      sections:
        - standard
        - default
        - prefix(github.com/good-listener)
      custom-order: true

linters:
  enable:
    # Bugs
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - govet
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck

    # Complexity
    - cyclop
    - funlen
    - gocognit
    - nestif

    # Metalinters
    - gocritic
    - revive

    # Module
    - gomoddirectives

    # Performance
    - prealloc

    # Style
    - dogsled
    - dupword
    - errname
    - errorlint
    - godot
    - misspell
    - nakedret
    - nolintlint
    - predeclared
    - unconvert
    - unparam
    - whitespace

    # Unused
    - ineffassign
    - unused

    # Security
    - gosec

  settings:
    cyclop:
      max-complexity: 15
      skip-tests: true

    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (net.Conn).Close
        - (*os/exec.Cmd).Wait
        - (github.com/coder/websocket.Conn).Close
        - os.Remove
        - os.RemoveAll
        - os.Setenv
        - os.Unsetenv
        - rand.Read
        - (*encoding/json.Encoder).Encode
        - (github.com/coder/websocket/wsjson).Write

    funlen:
      lines: 100
      statements: 50

    gocognit:
      min-complexity: 20

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
        - commentedOutCode
        - rangeValCopy
        - singleCaseSwitch

    gosec:
      excludes:
        - G104  # Audit errors not checked (handled by errcheck)
        - G115  # Integer overflow (intentional conversions)
        - G204  # Subprocess with variable (screencapture is safe)
        - G304  # File inclusion via variable (our temp files)
        - G401  # Use of weak crypto (md5 for content hashing, not security)
        - G501  # Blocklisted import md5 (same as above)

    govet:
      enable-all: true
      disable:
        - fieldalignment

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    nestif:
      min-complexity: 5

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    prealloc:
      simple: true
      for-loops: true

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true  # Too noisy for internal types
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id

    staticcheck:
      checks:
        - all
        - -SA1019  # Deprecated (grpc.Dial still works)

    unused:
      field-writes-are-uses: false
      exported-fields-are-used: true
      local-variables-are-used: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - vendor
    - third_party
    - testdata
    - pkg/pb

  exclude-rules:
    # Allow globals in main
    - path: cmd/
      linters:
        - gochecknoglobals

    # Generated code (protobuf)
    - path: \.pb\.go$
      linters:
        - errcheck
        - govet
        - unused
        - staticcheck
        - revive
        - gocritic
        - gosec
