// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder - regenerate with `make proto`

package pb

// TranscribeRequest is the request for transcription
type TranscribeRequest struct {
	AudioData  []byte
	SampleRate int32
	Language   string
}

// TranscribeResponse is the response from transcription
type TranscribeResponse struct {
	Text       string
	Confidence float64
	DurationMs int64
}

// AudioChunk is a chunk of audio for streaming
type AudioChunk struct {
	Data        []byte
	TimestampNs int64
	DeviceId    string
}

// TranscriptSegment is a segment of transcribed text
type TranscriptSegment struct {
	Text     string
	DeviceId string
	StartNs  int64
	EndNs    int64
	IsFinal  bool
}

// OCRRequest is the request for OCR
type OCRRequest struct {
	ImageData []byte
	Format    string
}

// OCRResponse is the response from OCR
type OCRResponse struct {
	Text  string
	Boxes []*BoundingBox
}

// BoundingBox represents a text region
type BoundingBox struct {
	X1, Y1, X2, Y2 int32
	Text           string
	Confidence     float32
}

// AnalyzeRequest is the request for LLM analysis
type AnalyzeRequest struct {
	ContextText string
	UserQuery   string
	ImageData   []byte
	Transcript  string
}

// AnalyzeChunk is a streaming chunk from LLM
type AnalyzeChunk struct {
	Content string
	IsFinal bool
}

// IsQuestionRequest is the request to check if text is a question
type IsQuestionRequest struct {
	Text string
}

// IsQuestionResponse is the response for question detection
type IsQuestionResponse struct {
	IsQuestion bool
}

// StoreRequest is the request to store memory
type StoreRequest struct {
	Text     string
	Source   string
	Metadata map[string]string
}

// StoreResponse is the response from storing memory
type StoreResponse struct {
	Id      string
	Success bool
}

// QueryRequest is the request to query memory
type QueryRequest struct {
	QueryText    string
	NResults     int32
	SourceFilter string
}

// QueryResponse is the response from querying memory
type QueryResponse struct {
	Documents []string
	Scores    []float32
}

// ClearRequest is the request to clear memory
type ClearRequest struct{}

// ClearResponse is the response from clearing memory
type ClearResponse struct {
	DeletedCount int32
}

// VADRequest is the request for voice activity detection
type VADRequest struct {
	AudioChunk []byte
	SampleRate int32
}

// VADResponse is the response from VAD
type VADResponse struct {
	SpeechProbability float32
	IsSpeech          bool
}

// ResetStateRequest is the request to reset VAD state
type ResetStateRequest struct{}

// ResetStateResponse is the response from resetting VAD state
type ResetStateResponse struct {
	Success bool
}
