// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a placeholder - regenerate with `make proto`

package pb

import (
	"context"

	"google.golang.org/grpc"
)

// TranscriptionServiceClient is the client API for TranscriptionService
type TranscriptionServiceClient interface {
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error)
	StreamTranscribe(ctx context.Context, opts ...grpc.CallOption) (TranscriptionService_StreamTranscribeClient, error)
}

type transcriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscriptionServiceClient(cc grpc.ClientConnInterface) TranscriptionServiceClient {
	return &transcriptionServiceClient{cc}
}

func (c *transcriptionServiceClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (*TranscribeResponse, error) {
	out := new(TranscribeResponse)
	err := c.cc.Invoke(ctx, "/cognition.TranscriptionService/Transcribe", in, out, opts...)
	return out, err
}

func (c *transcriptionServiceClient) StreamTranscribe(ctx context.Context, opts ...grpc.CallOption) (TranscriptionService_StreamTranscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName:    "StreamTranscribe",
		ServerStreams: true,
		ClientStreams: true,
	}, "/cognition.TranscriptionService/StreamTranscribe", opts...)
	if err != nil {
		return nil, err
	}
	return &transcriptionServiceStreamTranscribeClient{stream}, nil
}

type TranscriptionService_StreamTranscribeClient interface {
	Send(*AudioChunk) error
	Recv() (*TranscriptSegment, error)
	grpc.ClientStream
}

type transcriptionServiceStreamTranscribeClient struct {
	grpc.ClientStream
}

func (x *transcriptionServiceStreamTranscribeClient) Send(m *AudioChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transcriptionServiceStreamTranscribeClient) Recv() (*TranscriptSegment, error) {
	m := new(TranscriptSegment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VADServiceClient is the client API for VADService
type VADServiceClient interface {
	DetectSpeech(ctx context.Context, in *VADRequest, opts ...grpc.CallOption) (*VADResponse, error)
	ResetState(ctx context.Context, in *ResetStateRequest, opts ...grpc.CallOption) (*ResetStateResponse, error)
}

type vadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVADServiceClient(cc grpc.ClientConnInterface) VADServiceClient {
	return &vadServiceClient{cc}
}

func (c *vadServiceClient) DetectSpeech(ctx context.Context, in *VADRequest, opts ...grpc.CallOption) (*VADResponse, error) {
	out := new(VADResponse)
	err := c.cc.Invoke(ctx, "/cognition.VADService/DetectSpeech", in, out, opts...)
	return out, err
}

func (c *vadServiceClient) ResetState(ctx context.Context, in *ResetStateRequest, opts ...grpc.CallOption) (*ResetStateResponse, error) {
	out := new(ResetStateResponse)
	err := c.cc.Invoke(ctx, "/cognition.VADService/ResetState", in, out, opts...)
	return out, err
}

// OCRServiceClient is the client API for OCRService
type OCRServiceClient interface {
	ExtractText(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error)
}

type ocrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOCRServiceClient(cc grpc.ClientConnInterface) OCRServiceClient {
	return &ocrServiceClient{cc}
}

func (c *ocrServiceClient) ExtractText(ctx context.Context, in *OCRRequest, opts ...grpc.CallOption) (*OCRResponse, error) {
	out := new(OCRResponse)
	err := c.cc.Invoke(ctx, "/cognition.OCRService/ExtractText", in, out, opts...)
	return out, err
}

// LLMServiceClient is the client API for LLMService
type LLMServiceClient interface {
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (LLMService_AnalyzeClient, error)
	IsQuestion(ctx context.Context, in *IsQuestionRequest, opts ...grpc.CallOption) (*IsQuestionResponse, error)
}

type llmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &llmServiceClient{cc}
}

func (c *llmServiceClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (LLMService_AnalyzeClient, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName:    "Analyze",
		ServerStreams: true,
	}, "/cognition.LLMService/Analyze", opts...)
	if err != nil {
		return nil, err
	}
	x := &llmServiceAnalyzeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LLMService_AnalyzeClient interface {
	Recv() (*AnalyzeChunk, error)
	grpc.ClientStream
}

type llmServiceAnalyzeClient struct {
	grpc.ClientStream
}

func (x *llmServiceAnalyzeClient) Recv() (*AnalyzeChunk, error) {
	m := new(AnalyzeChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *llmServiceClient) IsQuestion(ctx context.Context, in *IsQuestionRequest, opts ...grpc.CallOption) (*IsQuestionResponse, error) {
	out := new(IsQuestionResponse)
	err := c.cc.Invoke(ctx, "/cognition.LLMService/IsQuestion", in, out, opts...)
	return out, err
}

// MemoryServiceClient is the client API for MemoryService
type MemoryServiceClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, "/cognition.MemoryService/Store", in, out, opts...)
	return out, err
}

func (c *memoryServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/cognition.MemoryService/Query", in, out, opts...)
	return out, err
}

func (c *memoryServiceClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, "/cognition.MemoryService/Clear", in, out, opts...)
	return out, err
}
