// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: cognition.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`     // PCM float32 audio at 16kHz
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // Sample rate (default 16000)
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                        // Optional language hint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_cognition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TranscribeRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *TranscribeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type TranscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_cognition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{1}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscribeResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                   // PCM float32 audio chunk
	TimestampNs   int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // Nanosecond timestamp
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`           // Source device identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_cognition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *AudioChunk) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type TranscriptSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	StartNs       int64                  `protobuf:"varint,3,opt,name=start_ns,json=startNs,proto3" json:"start_ns,omitempty"`
	EndNs         int64                  `protobuf:"varint,4,opt,name=end_ns,json=endNs,proto3" json:"end_ns,omitempty"`
	IsFinal       bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptSegment) Reset() {
	*x = TranscriptSegment{}
	mi := &file_cognition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptSegment) ProtoMessage() {}

func (x *TranscriptSegment) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptSegment.ProtoReflect.Descriptor instead.
func (*TranscriptSegment) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{3}
}

func (x *TranscriptSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptSegment) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TranscriptSegment) GetStartNs() int64 {
	if x != nil {
		return x.StartNs
	}
	return 0
}

func (x *TranscriptSegment) GetEndNs() int64 {
	if x != nil {
		return x.EndNs
	}
	return 0
}

func (x *TranscriptSegment) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type OCRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // JPEG or PNG encoded image
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                        // "jpeg" or "png"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRRequest) Reset() {
	*x = OCRRequest{}
	mi := &file_cognition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRRequest) ProtoMessage() {}

func (x *OCRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRRequest.ProtoReflect.Descriptor instead.
func (*OCRRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{4}
}

func (x *OCRRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *OCRRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type OCRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Boxes         []*BoundingBox         `protobuf:"bytes,2,rep,name=boxes,proto3" json:"boxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCRResponse) Reset() {
	*x = OCRResponse{}
	mi := &file_cognition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRResponse) ProtoMessage() {}

func (x *OCRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRResponse.ProtoReflect.Descriptor instead.
func (*OCRResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{5}
}

func (x *OCRResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OCRResponse) GetBoxes() []*BoundingBox {
	if x != nil {
		return x.Boxes
	}
	return nil
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            int32                  `protobuf:"varint,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            int32                  `protobuf:"varint,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            int32                  `protobuf:"varint,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            int32                  `protobuf:"varint,4,opt,name=y2,proto3" json:"y2,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_cognition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{6}
}

func (x *BoundingBox) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *BoundingBox) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *BoundingBox) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *BoundingBox) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *BoundingBox) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *BoundingBox) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContextText   string                 `protobuf:"bytes,1,opt,name=context_text,json=contextText,proto3" json:"context_text,omitempty"` // OCR/screen text
	UserQuery     string                 `protobuf:"bytes,2,opt,name=user_query,json=userQuery,proto3" json:"user_query,omitempty"`       // User's question
	ImageData     []byte                 `protobuf:"bytes,3,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`       // Optional screenshot (JPEG)
	Transcript    string                 `protobuf:"bytes,4,opt,name=transcript,proto3" json:"transcript,omitempty"`                      // Recent conversation transcript
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_cognition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeRequest) GetContextText() string {
	if x != nil {
		return x.ContextText
	}
	return ""
}

func (x *AnalyzeRequest) GetUserQuery() string {
	if x != nil {
		return x.UserQuery
	}
	return ""
}

func (x *AnalyzeRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *AnalyzeRequest) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

type AnalyzeChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeChunk) Reset() {
	*x = AnalyzeChunk{}
	mi := &file_cognition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeChunk) ProtoMessage() {}

func (x *AnalyzeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeChunk.ProtoReflect.Descriptor instead.
func (*AnalyzeChunk) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnalyzeChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type IsQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsQuestionRequest) Reset() {
	*x = IsQuestionRequest{}
	mi := &file_cognition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsQuestionRequest) ProtoMessage() {}

func (x *IsQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsQuestionRequest.ProtoReflect.Descriptor instead.
func (*IsQuestionRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{9}
}

func (x *IsQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type IsQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsQuestion    bool                   `protobuf:"varint,1,opt,name=is_question,json=isQuestion,proto3" json:"is_question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsQuestionResponse) Reset() {
	*x = IsQuestionResponse{}
	mi := &file_cognition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsQuestionResponse) ProtoMessage() {}

func (x *IsQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsQuestionResponse.ProtoReflect.Descriptor instead.
func (*IsQuestionResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{10}
}

func (x *IsQuestionResponse) GetIsQuestion() bool {
	if x != nil {
		return x.IsQuestion
	}
	return false
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // "audio" or "screen"
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_cognition_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{11}
}

func (x *StoreRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StoreRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StoreRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_cognition_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{12}
}

func (x *StoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BatchStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoreRequest        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreRequest) Reset() {
	*x = BatchStoreRequest{}
	mi := &file_cognition_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreRequest) ProtoMessage() {}

func (x *BatchStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreRequest.ProtoReflect.Descriptor instead.
func (*BatchStoreRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{13}
}

func (x *BatchStoreRequest) GetItems() []*StoreRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	StoredCount   int32                  `protobuf:"varint,2,opt,name=stored_count,json=storedCount,proto3" json:"stored_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreResponse) Reset() {
	*x = BatchStoreResponse{}
	mi := &file_cognition_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreResponse) ProtoMessage() {}

func (x *BatchStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreResponse.ProtoReflect.Descriptor instead.
func (*BatchStoreResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{14}
}

func (x *BatchStoreResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchStoreResponse) GetStoredCount() int32 {
	if x != nil {
		return x.StoredCount
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryText     string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	NResults      int32                  `protobuf:"varint,2,opt,name=n_results,json=nResults,proto3" json:"n_results,omitempty"`
	SourceFilter  string                 `protobuf:"bytes,3,opt,name=source_filter,json=sourceFilter,proto3" json:"source_filter,omitempty"` // Optional: filter by source
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_cognition_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{15}
}

func (x *QueryRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *QueryRequest) GetNResults() int32 {
	if x != nil {
		return x.NResults
	}
	return 0
}

func (x *QueryRequest) GetSourceFilter() string {
	if x != nil {
		return x.SourceFilter
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []string               `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Scores        []float32              `protobuf:"fixed32,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_cognition_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{16}
}

func (x *QueryResponse) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *QueryResponse) GetScores() []float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_cognition_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{17}
}

type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_cognition_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{18}
}

func (x *ClearResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type VADRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioChunk    []byte                 `protobuf:"bytes,1,opt,name=audio_chunk,json=audioChunk,proto3" json:"audio_chunk,omitempty"` // 512 samples of float32 PCM
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VADRequest) Reset() {
	*x = VADRequest{}
	mi := &file_cognition_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VADRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VADRequest) ProtoMessage() {}

func (x *VADRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VADRequest.ProtoReflect.Descriptor instead.
func (*VADRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{19}
}

func (x *VADRequest) GetAudioChunk() []byte {
	if x != nil {
		return x.AudioChunk
	}
	return nil
}

func (x *VADRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type VADResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SpeechProbability float32                `protobuf:"fixed32,1,opt,name=speech_probability,json=speechProbability,proto3" json:"speech_probability,omitempty"`
	IsSpeech          bool                   `protobuf:"varint,2,opt,name=is_speech,json=isSpeech,proto3" json:"is_speech,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VADResponse) Reset() {
	*x = VADResponse{}
	mi := &file_cognition_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VADResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VADResponse) ProtoMessage() {}

func (x *VADResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VADResponse.ProtoReflect.Descriptor instead.
func (*VADResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{20}
}

func (x *VADResponse) GetSpeechProbability() float32 {
	if x != nil {
		return x.SpeechProbability
	}
	return 0
}

func (x *VADResponse) GetIsSpeech() bool {
	if x != nil {
		return x.IsSpeech
	}
	return false
}

type ResetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetStateRequest) Reset() {
	*x = ResetStateRequest{}
	mi := &file_cognition_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStateRequest) ProtoMessage() {}

func (x *ResetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStateRequest.ProtoReflect.Descriptor instead.
func (*ResetStateRequest) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{21}
}

type ResetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetStateResponse) Reset() {
	*x = ResetStateResponse{}
	mi := &file_cognition_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetStateResponse) ProtoMessage() {}

func (x *ResetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cognition_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetStateResponse.ProtoReflect.Descriptor instead.
func (*ResetStateResponse) Descriptor() ([]byte, []int) {
	return file_cognition_proto_rawDescGZIP(), []int{22}
}

func (x *ResetStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_cognition_proto protoreflect.FileDescriptor

const file_cognition_proto_rawDesc = "" +
	"\n" +
	"\x0fcognition.proto\x12\tcognition\"o\n" +
	"\x11TranscribeRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"i\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"`\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"\x91\x01\n" +
	"\x11TranscriptSegment\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bstart_ns\x18\x03 \x01(\x03R\astartNs\x12\x15\n" +
	"\x06end_ns\x18\x04 \x01(\x03R\x05endNs\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\"C\n" +
	"\n" +
	"OCRRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"O\n" +
	"\vOCRResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12,\n" +
	"\x05boxes\x18\x02 \x03(\v2\x16.cognition.BoundingBoxR\x05boxes\"\x81\x01\n" +
	"\vBoundingBox\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x05R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x05R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x05R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x05R\x02y2\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\"\x91\x01\n" +
	"\x0eAnalyzeRequest\x12!\n" +
	"\fcontext_text\x18\x01 \x01(\tR\vcontextText\x12\x1d\n" +
	"\n" +
	"user_query\x18\x02 \x01(\tR\tuserQuery\x12\x1d\n" +
	"\n" +
	"image_data\x18\x03 \x01(\fR\timageData\x12\x1e\n" +
	"\n" +
	"transcript\x18\x04 \x01(\tR\n" +
	"transcript\"C\n" +
	"\fAnalyzeChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\"'\n" +
	"\x11IsQuestionRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"5\n" +
	"\x12IsQuestionResponse\x12\x1f\n" +
	"\vis_question\x18\x01 \x01(\bR\n" +
	"isQuestion\"\xba\x01\n" +
	"\fStoreRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.cognition.StoreRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"B\n" +
	"\x11BatchStoreRequest\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.cognition.StoreRequestR\x05items\"I\n" +
	"\x12BatchStoreResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12!\n" +
	"\fstored_count\x18\x02 \x01(\x05R\vstoredCount\"o\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12\x1b\n" +
	"\tn_results\x18\x02 \x01(\x05R\bnResults\x12#\n" +
	"\rsource_filter\x18\x03 \x01(\tR\fsourceFilter\"E\n" +
	"\rQueryResponse\x12\x1c\n" +
	"\tdocuments\x18\x01 \x03(\tR\tdocuments\x12\x16\n" +
	"\x06scores\x18\x02 \x03(\x02R\x06scores\"\x0e\n" +
	"\fClearRequest\"4\n" +
	"\rClearResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"N\n" +
	"\n" +
	"VADRequest\x12\x1f\n" +
	"\vaudio_chunk\x18\x01 \x01(\fR\n" +
	"audioChunk\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\"Y\n" +
	"\vVADResponse\x12-\n" +
	"\x12speech_probability\x18\x01 \x01(\x02R\x11speechProbability\x12\x1b\n" +
	"\tis_speech\x18\x02 \x01(\bR\bisSpeech\"\x13\n" +
	"\x11ResetStateRequest\".\n" +
	"\x12ResetStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xae\x01\n" +
	"\x14TranscriptionService\x12I\n" +
	"\n" +
	"Transcribe\x12\x1c.cognition.TranscribeRequest\x1a\x1d.cognition.TranscribeResponse\x12K\n" +
	"\x10StreamTranscribe\x12\x15.cognition.AudioChunk\x1a\x1c.cognition.TranscriptSegment(\x010\x012J\n" +
	"\n" +
	"OCRService\x12<\n" +
	"\vExtractText\x12\x15.cognition.OCRRequest\x1a\x16.cognition.OCRResponse2\x98\x01\n" +
	"\n" +
	"LLMService\x12?\n" +
	"\aAnalyze\x12\x19.cognition.AnalyzeRequest\x1a\x17.cognition.AnalyzeChunk0\x01\x12I\n" +
	"\n" +
	"IsQuestion\x12\x1c.cognition.IsQuestionRequest\x1a\x1d.cognition.IsQuestionResponse2\x8e\x02\n" +
	"\rMemoryService\x12:\n" +
	"\x05Store\x12\x17.cognition.StoreRequest\x1a\x18.cognition.StoreResponse\x12I\n" +
	"\n" +
	"BatchStore\x12\x1c.cognition.BatchStoreRequest\x1a\x1d.cognition.BatchStoreResponse\x12:\n" +
	"\x05Query\x12\x17.cognition.QueryRequest\x1a\x18.cognition.QueryResponse\x12:\n" +
	"\x05Clear\x12\x17.cognition.ClearRequest\x1a\x18.cognition.ClearResponse2\x96\x01\n" +
	"\n" +
	"VADService\x12=\n" +
	"\fDetectSpeech\x12\x15.cognition.VADRequest\x1a\x16.cognition.VADResponse\x12I\n" +
	"\n" +
	"ResetState\x12\x1c.cognition.ResetStateRequest\x1a\x1d.cognition.ResetStateResponseB*Z(github.com/good-listener/platform/pkg/pbb\x06proto3"

var (
	file_cognition_proto_rawDescOnce sync.Once
	file_cognition_proto_rawDescData []byte
)

func file_cognition_proto_rawDescGZIP() []byte {
	file_cognition_proto_rawDescOnce.Do(func() {
		file_cognition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cognition_proto_rawDesc), len(file_cognition_proto_rawDesc)))
	})
	return file_cognition_proto_rawDescData
}

var file_cognition_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_cognition_proto_goTypes = []any{
	(*TranscribeRequest)(nil),  // 0: cognition.TranscribeRequest
	(*TranscribeResponse)(nil), // 1: cognition.TranscribeResponse
	(*AudioChunk)(nil),         // 2: cognition.AudioChunk
	(*TranscriptSegment)(nil),  // 3: cognition.TranscriptSegment
	(*OCRRequest)(nil),         // 4: cognition.OCRRequest
	(*OCRResponse)(nil),        // 5: cognition.OCRResponse
	(*BoundingBox)(nil),        // 6: cognition.BoundingBox
	(*AnalyzeRequest)(nil),     // 7: cognition.AnalyzeRequest
	(*AnalyzeChunk)(nil),       // 8: cognition.AnalyzeChunk
	(*IsQuestionRequest)(nil),  // 9: cognition.IsQuestionRequest
	(*IsQuestionResponse)(nil), // 10: cognition.IsQuestionResponse
	(*StoreRequest)(nil),       // 11: cognition.StoreRequest
	(*StoreResponse)(nil),      // 12: cognition.StoreResponse
	(*BatchStoreRequest)(nil),  // 13: cognition.BatchStoreRequest
	(*BatchStoreResponse)(nil), // 14: cognition.BatchStoreResponse
	(*QueryRequest)(nil),       // 15: cognition.QueryRequest
	(*QueryResponse)(nil),      // 16: cognition.QueryResponse
	(*ClearRequest)(nil),       // 17: cognition.ClearRequest
	(*ClearResponse)(nil),      // 18: cognition.ClearResponse
	(*VADRequest)(nil),         // 19: cognition.VADRequest
	(*VADResponse)(nil),        // 20: cognition.VADResponse
	(*ResetStateRequest)(nil),  // 21: cognition.ResetStateRequest
	(*ResetStateResponse)(nil), // 22: cognition.ResetStateResponse
	nil,                        // 23: cognition.StoreRequest.MetadataEntry
}
var file_cognition_proto_depIdxs = []int32{
	6,  // 0: cognition.OCRResponse.boxes:type_name -> cognition.BoundingBox
	23, // 1: cognition.StoreRequest.metadata:type_name -> cognition.StoreRequest.MetadataEntry
	11, // 2: cognition.BatchStoreRequest.items:type_name -> cognition.StoreRequest
	0,  // 3: cognition.TranscriptionService.Transcribe:input_type -> cognition.TranscribeRequest
	2,  // 4: cognition.TranscriptionService.StreamTranscribe:input_type -> cognition.AudioChunk
	4,  // 5: cognition.OCRService.ExtractText:input_type -> cognition.OCRRequest
	7,  // 6: cognition.LLMService.Analyze:input_type -> cognition.AnalyzeRequest
	9,  // 7: cognition.LLMService.IsQuestion:input_type -> cognition.IsQuestionRequest
	11, // 8: cognition.MemoryService.Store:input_type -> cognition.StoreRequest
	13, // 9: cognition.MemoryService.BatchStore:input_type -> cognition.BatchStoreRequest
	15, // 10: cognition.MemoryService.Query:input_type -> cognition.QueryRequest
	17, // 11: cognition.MemoryService.Clear:input_type -> cognition.ClearRequest
	19, // 12: cognition.VADService.DetectSpeech:input_type -> cognition.VADRequest
	21, // 13: cognition.VADService.ResetState:input_type -> cognition.ResetStateRequest
	1,  // 14: cognition.TranscriptionService.Transcribe:output_type -> cognition.TranscribeResponse
	3,  // 15: cognition.TranscriptionService.StreamTranscribe:output_type -> cognition.TranscriptSegment
	5,  // 16: cognition.OCRService.ExtractText:output_type -> cognition.OCRResponse
	8,  // 17: cognition.LLMService.Analyze:output_type -> cognition.AnalyzeChunk
	10, // 18: cognition.LLMService.IsQuestion:output_type -> cognition.IsQuestionResponse
	12, // 19: cognition.MemoryService.Store:output_type -> cognition.StoreResponse
	14, // 20: cognition.MemoryService.BatchStore:output_type -> cognition.BatchStoreResponse
	16, // 21: cognition.MemoryService.Query:output_type -> cognition.QueryResponse
	18, // 22: cognition.MemoryService.Clear:output_type -> cognition.ClearResponse
	20, // 23: cognition.VADService.DetectSpeech:output_type -> cognition.VADResponse
	22, // 24: cognition.VADService.ResetState:output_type -> cognition.ResetStateResponse
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cognition_proto_init() }
func file_cognition_proto_init() {
	if File_cognition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cognition_proto_rawDesc), len(file_cognition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_cognition_proto_goTypes,
		DependencyIndexes: file_cognition_proto_depIdxs,
		MessageInfos:      file_cognition_proto_msgTypes,
	}.Build()
	File_cognition_proto = out.File
	file_cognition_proto_goTypes = nil
	file_cognition_proto_depIdxs = nil
}
